routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//front end home route
Route::get('/', function () {
    return view('frontend.index');
});

Auth::routes();

//backend home route
Route::get('/dashboard', 'HomeController@index')->name('home');

//register Route
Route::get('/new-register', function () {
    return view('auth.register');
});

//user list route
Route::get('/user-list', 'HomeController@userList')->name('user-list');

//Category Setup
Route::resource('/category', 'Setup\CategoryController')->parameter('category','id');

//Writer Setup
Route::resource('/writer', 'Setup\WriterController')->parameter('writer','id');

//Book
Route::resource('/book', 'Book\BookController')->parameter('book','id');

//Student
Route::resource('/student', 'Student\StudentController')->parameter('student','id');

//Book Issue
Route::resource('/book-issue', 'BookIssue\BookIssueController')->parameter('book-issue','id');
Route::get('/book-issue/get-book/{id}', 'BookIssue\BookIssueController@getCategoryWiseBook');
Route::get('/book-issue/get-class-wise-student/{id}', 'BookIssue\BookIssueController@getClassWiseStudent');

//book issue due list 
Route::get('/due-book-issue-list', 'BookIssue\BookIssueController@dueBookIssuelist')->name('due-book-issue-list');

//activity list 
Route::get('/activity-list', 'BookIssue\BookIssueController@activityList')->name('activity-list');

//fine list 
Route::get('/fine-list', 'BookIssue\BookIssueController@fineList')->name('fine-list');

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Setup\Category;
use App\Models\Setup\Writer;

class Book extends Model
{
    protected $fillable=['name','category_id','writer_id','price','description','language','image','created_by','updated_by'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function writer()
    {
        return $this->belongsTo(Writer::class);
    }

}

app/Http/Controllers/Book/BookController.php
<?php

namespace App\Http\Controllers\Book;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use App\Models\Book;
use App\Models\Setup\Category;
use App\Models\Setup\Writer;
use Auth;

class BookController extends Controller
{

    public function index()
    {
        $book=Book::all();
        $category=Category::all();
        return view('backend.book.index',compact("book","category"));
    }

    public function create()
    {
        $category=Category::get()->all();
        $writer=Writer::get()->all();
        return view('backend.book.create',compact("category","writer"));
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required',
            'category_id'=>'required',
            'writer_id'=>'required',
            'language'=>'required',
        ]);

        $book=new Book();
        $book->name=$request->name;
        $book->category_id=$request->category;
        $book->writer_id=$request->writer;
        $book->price=$request->price;
        $book->description=$request->description;
        $book->language=$request->language;
        $book->created_by=Auth::id();

        //file Upload
        if ($request->hasFile('file')){
            $file=$request->file('file');
            $extension=$file->getClientOriginalExtension();
            $fileName = time().'.'. $extension;
            $file->move('uploads',$fileName);
            $book->image=$fileName;

        }
        else
        {
            $book->image='';
        }

        $book->save();
        return redirect(route('book.index'));
    }

    public function show($id)
    {
        $book=Book::findorFail($id);
        return view('backend.book.show',compact("book"))->with('success','Book Has been Created Successfully');
    }

    public function edit($id)
    {
        $bookData=Book::findorFail($id);
        $category=Category::get()->all();
        $writer=Writer::get()->all();
        return view('backend.book.edit',compact("bookData","category","writer"));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name'=>'required',
            'category_id'=>'required',
            'writer_id'=>'required',
            'language'=>'required',
        ]);

        $file_name=$request->hidden_file;

        if ($request->hasFile('file')){
            $file=$request->file('file');
            $extension=$file->getClientOriginalExtension();
            $fileName = time().'.'. $extension;
            $file->move('uploads',$fileName);
            $image=$fileName;

        }
        else
        {
            $image=$file_name;
        }

        $edited_data=array(
            'name'=>$request->name,
            'category_id'=>$request->category,
            'writer_id'=>$request->writer,
            'price'=>$request->price,
            'description'=>$request->description,
            'language'=>$request->language,
            'image'=>$image,
            'updated_by'=>Auth::id()

        );

        Book::whereId($id)->update($edited_data);
        return redirect(route('book.index'))->with('success','Book Has been Updated Successfully');
    }

    public function destroy($id)
    {
        $bookData=Book::findorFail($id);
        $bookData->delete();
        return redirect()->route('book.index');

    }
}

resources/views/backend/book/create.blade.php
@extends('backend.layout.master')

@section('title', 'Add Book')

@section('content')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3> Add New Book</h3>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <form class="form-horizontal" method="POST" action ="{{route('book.store')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <!-- name -->
                                <div class="form-group row">
                                    <label for="name" class="col-sm-2 col-form-label">Book Name<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                    <input type="text" class="form-control" name="name" placeholder="Book Name" required>
                                    </div>
                                </div>
                                <!-- category -->
                                <div class="form-group row">
                                    <label for="category" class="col-sm-2 col-form-label">Category Name<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                        <select name="category" class="form-control" required>
                                            <option value="" selected>-Select Category-</option>
                                            @foreach($category as $model)
                                                <option value="{{$model->id}}">{{$model->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <!-- Writer -->
                                <div class="form-group row">
                                    <label for="writer" class="col-sm-2 col-form-label">Writer Name<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                        <select name="writer" class="form-control" required>
                                            <option value="" selected>-Select Writer-</option>
                                            @foreach($writer as $model)
                                                <option value="{{$model->id}}">{{$model->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <!-- description -->
                                <div class="form-group row">
                                    <label for="description" class="col-sm-2 col-form-label">Book Description</label>
                                    <div class="col-sm-8">
                                        <textarea class="form-control" name="description" rows="3" placeholder="Enter Description"></textarea>
                                    </div>
                                </div>
                                <!-- Language -->
                                <div class="form-group row">
                                    <label for="language" class="col-sm-2 col-form-label">Language</label>
                                    <div class="col-sm-8">
                                        <select name="language" class="form-control">
                                            <option value="" selected>-Select Language-</option>
                                            <option value="english">English</option>
                                            <option value="bangla">Bangla</option>
                                            <option value="arabic">Arabic</option>
                                            <option value="other">Other</option>
                                        </select>
                                    </div>
                                </div>
                                <!-- price -->
                                <div class="form-group row">
                                    <label for="price" class="col-sm-2 col-form-label">Book Price</label>
                                    <div class="col-sm-8">
                                    <input type="number" class="form-control" name="price" placeholder="Book Price">
                                    </div>
                                </div>
                                <!-- Upload File -->
                                <div class="form-group row">
                                    <label for="file" class="col-sm-2 col-form-label">Upload File/Image</label>
                                    <div class="col-sm-8">
                                    <input type="file" class="custom-file-upload" name="file">
                                    </div>
                                </div>

                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer float-right">
                                <input type="submit" class="btn btn-success ">
                                <a  class="btn btn-danger" href="{{route('book.create')}}" role="button">Reset</a>
                                <a  class="btn btn-primary" href="{{route('book.index')}}" role="button">Back</a>
                            </div>
                            <!-- /.card-footer -->
                        </form>
                        <!-- /.card-body -->
                    </div>

                </div>
            </div>
        </div>
            <!-- /.container-fluid -->
    </section>
</div>


@endsection

resources/views/backend/book/edit.blade.php
@extends('backend.layout.master')

@section('title', 'Edit Book')

@section('content')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3> Add New Book</h3>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        
                        {{ Form::open(['route'=>['book.update',$bookData->id], 'method'=>'PUT' ,'class'=>'form-horizontal','files'=> true]) }}

                            @csrf
                            <div class="card-body">
                                <!-- name -->
                                <div class="form-group row">
                                    <label for="name" class="col-sm-2 col-form-label">Book Name<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                    <input type="text" class="form-control" name="name" placeholder="Book Name" value="{{$bookData->name}}"required>
                                    </div>
                                </div>
                                <!-- category -->
                                <div class="form-group row">
                                    <label for="category" class="col-sm-2 col-form-label">Category Name<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                        <select name="category" class="form-control" required>
                                            <option value="{{$bookData->category_id}}" selected>{{$bookData->category->name}}</option>
                                            @foreach($category as $model)
                                                <option value="{{$model->id}}">{{$model->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <!-- Writer -->
                                <div class="form-group row">
                                    <label for="writer" class="col-sm-2 col-form-label">Writer Name<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                        <select name="writer" class="form-control" required>
                                            <option value="{{$bookData->writer_id}}" selected>{{$bookData->writer->name}}</option>
                                            @foreach($writer as $model)
                                                <option value="{{$model->id}}">{{$model->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <!-- description -->
                                <div class="form-group row">
                                    <label for="description" class="col-sm-2 col-form-label">Book Description</label>
                                    <div class="col-sm-8">
                                        <textarea class="form-control" name="description" rows="3" >{{$bookData->description}}</textarea>
                                    </div>
                                </div>
                                <!-- Language -->
                                <div class="form-group row">
                                    <label for="language" class="col-sm-2 col-form-label">Language</label>
                                    <div class="col-sm-8">
                                        <select name="language" class="form-control" >
                                            <option value="">-Select Language-</option>
                                            <option value="english" {{ $bookData->language=='english' ? 'selected' : ''}}>English</option>
                                            <option value="bangla" {{ $bookData->language=='bangla' ? 'selected' : ''}}>Bangla</option>
                                            <option value="arabic" {{ $bookData->language=='arabic' ? 'selected' : ''}}>Arabic</option>
                                            <option value="other" {{ $bookData->language=='other' ? 'selected' : ''}}>Other</option>
                                        </select>                                    
                                    </div>
                                </div>
                                <!-- price -->
                                <div class="form-group row">
                                    <label for="price" class="col-sm-2 col-form-label">Book Price</label>
                                    <div class="col-sm-8">
                                    <input type="number" class="form-control" name="price" value="{{$bookData->price}}" placeholder="Book Price">
                                    </div>
                                </div>
                                <!-- Upload File -->
                                <div class="form-group row">
                                    <label for="file" class="col-sm-2 col-form-label">Upload File/Image</label>
                                    <div class="col-sm-8">
                                    <input type="file" class="custom-file-upload" name="file">
                                    <img src="/uploads/{{$bookData->image}}" width="100" class="img-thumbnail">
                                    <input type="hidden"  name="hidden_file" value="{{$bookData->image}}">
                                    </div>
                                </div>

                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer float-right">
                            {{ Form::submit('Submit',['class'=>'btn btn-success']) }}
                                <a  class="btn btn-danger" href="{{route('book.create')}}" role="button">Reset</a>
                                <a  class="btn btn-primary" href="{{route('book.index')}}" role="button">Back</a>
                            </div>
                            <!-- /.card-footer -->
                        {{ Form::close() }}
                        <!-- /.card-body -->
                    </div>

                </div>
            </div>
        </div>
            <!-- /.container-fluid -->
    </section>
</div>


@endsection

resources/views/backend/book/index.blade.php
@extends('backend.layout.master')

@section('title', 'Book List')

@section('content')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Book List</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        @if(Auth::User()->status==1)
                        <div class="card-header" style="text-align:right;">
                            <a  class="btn btn-primary" href="{{route('book.create')}}" role="button">Add New Book</a>
                        </div>
                        @endif
                        <!-- /.card-header -->
                        <div class="card-body">
                          <div class="col-12">
                            <?php
                              $i=1;
                            ?>
                            <table id="example1" class="table table-bordered table-striped">
                              <thead>
                              <tr>
                                <th width="5%">Serial No.</th>
                                <th>Book Name</th>
                                <th>Category</th>
                                <th>Writer Name</th>
                                <th>Language</th>
                                @if(Auth::User()->status==1)
                                <th>Action</th>
                                @endif
                              </tr>
                              </thead>

                              @foreach($book as $model)
                              <tr>
                                <td>{{$i++}}</td>
                                <td>{{$model->name}}</td>
                                <td>{{$model->category->name}}</td>
                                <td>{{$model->writer->name}}</td>
                                <td>{{$model->language}}</td>

                                @if(Auth::User()->status==1)
                                <td>
                                <a  class="btn btn-info" href="{{route('book.show',$model->id)}}" role="button">View</a>
                                <a  class="btn btn-primary" href="{{route('book.edit',$model->id)}}" role="button">Edit</a>
                                {{ Form::open(['route'=>['book.destroy',$model->id], 'method'=>'delete' ,'class'=>'form-horizontal','files'=> true,'style' => 'display:inline',]) }}
                                {{ Form::submit('Delete',['class'=>'btn btn-danger','onclick' => 'return confirm("Are You Sure Want To Delete ?")']) }}
                                {{ Form::close() }}
                                </td>
                                @endif
                              </tr>
                              @endforeach()
                            </table>
                          </div>
                        </div>
                        <!-- /.card-body -->
                    </div>

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
</div>


@endsection

resources/views/backend/book/show.blade.php
@extends('backend.layout.master')

@section('content')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Book List</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header" style="text-align:right;">
                            <a  class="btn btn-primary" href="{{route('book.index')}}" role="button">Back To Book List</a>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                          <div class="col-112"> 
                            <table id="example1" class="table table-bordered table-striped" style="width:100%">
                              <thead>
                              <tr>
                                <th>Book Name</th>
                                <th>Category</th>
                                <th>Writer Name</th>
                                <th>Description</th>
                                <th>Language</th>
                                <th>Price</th>
                                <th>Image</th>
                              </tr>
                              </thead>
                              
                              <tr>
                                <td>{{$book->name}}</td>
                                <td>{{$book->category->name}}</td>
                                <td>{{$book->writer->name}}</td>
                                <td>{{$book->description}}</td>
                                <td>{{$book->language}}</td>
                                <td>{{$book->price}}</td>
                                <td><img src="/uploads/{{$book->image}}" width="100" class="img-thumbnail"></td>
                              </tr>
                              
                            </table>
                          </div>  
                        </div>
                        <!-- /.card-body -->
                    </div>

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
</div>


@endsection