routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//front end home route
Route::get('/', function () {
    return view('frontend.index');
});

Auth::routes();

//backend home route
Route::get('/dashboard', 'HomeController@index')->name('home');

//register Route
Route::get('/new-register', function () {
    return view('auth.register');
});

//user list route
Route::get('/user-list', 'HomeController@userList')->name('user-list');

//Category Setup
Route::resource('/category', 'Setup\CategoryController')->parameter('category','id');

//Writer Setup
Route::resource('/writer', 'Setup\WriterController')->parameter('writer','id');

//Book
Route::resource('/book', 'Book\BookController')->parameter('book','id');

//Student
Route::resource('/student', 'Student\StudentController')->parameter('student','id');

//Book Issue
Route::resource('/book-issue', 'BookIssue\BookIssueController')->parameter('book-issue','id');
Route::get('/book-issue/get-book/{id}', 'BookIssue\BookIssueController@getCategoryWiseBook');
Route::get('/book-issue/get-class-wise-student/{id}', 'BookIssue\BookIssueController@getClassWiseStudent');

//book issue due list 
Route::get('/due-book-issue-list', 'BookIssue\BookIssueController@dueBookIssuelist')->name('due-book-issue-list');

//activity list 
Route::get('/activity-list', 'BookIssue\BookIssueController@activityList')->name('activity-list');

//fine list 
Route::get('/fine-list', 'BookIssue\BookIssueController@fineList')->name('fine-list');

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable=['name','student_id','class','gender','image','created_by','updated_by'];
}

app/Http/Controllers/Student/StudentController.php
<?php

namespace App\Http\Controllers\Student;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Student;
use Auth;

class StudentController extends Controller
{

    public function index()
    {
        $studentData=Student::all();//dd($studentData);
        return view('backend.student.index',compact("studentData"));
    }

    public function create()
    {

        return view('backend.student.create');
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required',
            'student_id'=>'required',
            'class'=>'required',
            'gender'=>'required',
        ]);

        $student=new Student();
        $student->name=$request->name;
        $student->student_id=$request->student_id;
        $student->class=$request->class;
        $student->gender=$request->gender;
        $student->member_id=rand();
        $student->created_by=Auth::id();

        //file Upload
        if ($request->hasFile('file')){
            $file=$request->file('file');
            $extension=$file->getClientOriginalExtension();
            $fileName = time().'.'. $extension;
            $file->move('uploads',$fileName);
            $student->image=$fileName;

        }
        else
        {
            $student->image='';
        }

        $student->save();
        return redirect(route('student.index'))->with('success','Student Has been Created Successfully');
    }

    public function edit($id)
    {
        $studentData=Student::findorFail($id);
        return view('backend.student.edit',compact("studentData"));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name'=>'required',
            'student_id'=>'required',
            'class'=>'required',
            'gender'=>'required',
        ]);

        $file_name=$request->hidden_file;

        if ($request->hasFile('file')){
            $file=$request->file('file');
            $extension=$file->getClientOriginalExtension();
            $fileName = time().'.'. $extension;
            $file->move('uploads',$fileName);
            $image=$fileName;

        }
        else
        {
            $image=$file_name;
        }

        $edited_data=array(
            'name'=>$request->name,
            'student_id'=>$request->student_id,
            'class'=>$request->class,
            'gender'=>$request->gender,
            'member_id'=>$request->member_id,
            'image'=>$image,
            'updated_by'=>Auth::id()

        );

        Student::whereId($id)->update($edited_data);
        return redirect(route('student.index'))->with('success','Student Has been Updated Successfully');
    }

    public function destroy($id)
    {
        $student=Student::findorFail($id);
        $student->delete();
        return redirect()->route('student.index')->with('success','Student Has been Deleted Successfully');

    }
}

resources/views/backend/student/create.blade.php
@extends('backend.layout.master')

@section('title', 'Add Student')

@section('content')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3> Add New Student</h3>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <form class="form-horizontal" method="POST" action ="{{route('student.store')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <!-- name -->
                                <div class="form-group row">
                                    <label for="name" class="col-sm-2 col-form-label">Student Name<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                    <input type="text" class="form-control" name="name" placeholder="Enter Student Name" required>
                                    </div>
                                </div>
                                <!-- student_id -->
                                <div class="form-group row">
                                    <label for="student_id" class="col-sm-2 col-form-label">Student ID<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                    <input type="text" class="form-control" name="student_id" placeholder="Enter Student Id" required>
                                    </div>
                                </div>
                                <!-- class -->
                                <div class="form-group row">
                                    <label for="class" class="col-sm-2 col-form-label">Class<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                        <select name="class" class="form-control" required>
                                            <option value="" selected>-Select Class-</option>
                                            <option value="6">Six</option>
                                            <option value="7">Seven</option>
                                            <option value="8">Eight</option>
                                            <option value="9">Nine</option>
                                            <option value="10">Ten</option>
                                        </select>
                                    </div>
                                </div>
                                <!-- Gender -->
                                <div class="form-group row">
                                    <label for="gender" class="col-sm-2 col-form-label">Gender<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                        <select name="gender" class="form-control" required>
                                            <option value="" selected>-Select Gender-</option>
                                            <option value="male">Male</option>
                                            <option value="female">Female</option>
                                            <option value="other">Other</option>
                                        </select>
                                    </div>
                                </div>
                                <!-- Upload File -->
                                <div class="form-group row">
                                    <label for="file" class="col-sm-2 col-form-label">Image</label>
                                    <div class="col-sm-8">
                                    <input type="file" class="custom-file-upload" name="file">
                                    </div>
                                </div>

                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer float-right">
                                <input type="submit" class="btn btn-success ">
                                <a  class="btn btn-danger" href="{{route('student.create')}}" role="button">Reset</a>
                                <a  class="btn btn-primary" href="{{route('student.index')}}" role="button">Back</a>
                            </div>
                            <!-- /.card-footer -->
                        </form>
                        <!-- /.card-body -->
                    </div>

                </div>
            </div>
        </div>
            <!-- /.container-fluid -->
    </section>
</div>


@endsection

resources/views/backend/student/edit.blade.php
@extends('backend.layout.master')

@section('title', 'Edit Student')

@section('content')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3> Edit Student</h3>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        {{ Form::open(['route'=>['student.update',$studentData->id], 'method'=>'PUT' ,'class'=>'form-horizontal','files'=> true]) }}
                            @csrf
                            <div class="card-body">
                                <!-- member_id -->
                                <div class="form-group row">
                                    <label for="member_id" class="col-sm-2 col-form-label">Member ID<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                    <input type="text" class="form-control" name="member_id" placeholder="Enter Member Id" readonly value="{{$studentData->member_id}}">
                                    </div>
                                </div>
                                <!-- name -->
                                <div class="form-group row">
                                    <label for="name" class="col-sm-2 col-form-label">Student Name<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                    <input type="text" class="form-control" name="name" placeholder="Enter Student Name" value="{{$studentData->name}}" required>
                                    </div>
                                </div>
                                <!-- student_id -->
                                <div class="form-group row">
                                    <label for="student_id" class="col-sm-2 col-form-label">Student ID<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                    <input type="text" class="form-control" name="student_id" placeholder="Enter Student Id" value="{{$studentData->student_id}}" required>
                                    </div>
                                </div>
                                <!-- class -->
                                <div class="form-group row">
                                    <label for="class" class="col-sm-2 col-form-label">Class<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                        <select name="class" class="form-control" required>
                                            <option value="" selected>-Select Class-</option>
                                            <option value="6" {{ $studentData->class=='6' ? 'selected' : ''}}>Six</option>
                                            <option value="7" {{ $studentData->class=='7' ? 'selected' : ''}}>Seven</option>
                                            <option value="8" {{ $studentData->class=='8' ? 'selected' : ''}}>Eight</option>
                                            <option value="9" {{ $studentData->class=='9' ? 'selected' : ''}}>Nine</option>
                                            <option value="10" {{ $studentData->class=='10' ? 'selected' : ''}}>Ten</option>
                                        </select>
                                    </div>
                                </div>
                                <!-- Gender -->
                                <div class="form-group row">
                                    <label for="gender" class="col-sm-2 col-form-label">Gender<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                        <select name="gender" class="form-control" required>
                                            <option value="" selected>-Select Gender-</option>
                                            <option value="male" {{ $studentData->gender=='male' ? 'selected' : ''}}>Male</option>
                                            <option value="female" {{ $studentData->gender=='female' ? 'selected' : ''}}>Female</option>
                                            <option value="other" {{ $studentData->gender=='other' ? 'selected' : ''}}>Other</option>
                                        </select>
                                    </div>
                                </div>
                                <!-- Upload File -->
                                <div class="form-group row">
                                    <label for="file" class="col-sm-2 col-form-label">Image</label>
                                    <div class="col-sm-8">
                                    <input type="file" class="custom-file-upload" name="file">
                                    <img src="/uploads/{{$studentData->image}}" width="100" class="img-thumbnail">
                                    <input type="hidden"  name="hidden_file" value="{{$studentData->image}}">
                                    </div>
                                </div>

                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer float-right">
                            {{ Form::submit('Submit',['class'=>'btn btn-success']) }}
                                <a  class="btn btn-danger" href="{{route('student.create')}}" role="button">Reset</a>
                                <a  class="btn btn-primary" href="{{route('student.index')}}" role="button">Back</a>
                            </div>
                            <!-- /.card-footer -->
                        {{ Form::close() }}
                        <!-- /.card-body -->
                    </div>

                </div>
            </div>
        </div>
            <!-- /.container-fluid -->
    </section>
</div>


@endsection

resources/views/backend/student/index.blade.php
@extends('backend.layout.master')

@section('title', 'Student List')

@section('content')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Student List</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header" style="text-align:right;">
                            <a  class="btn btn-primary" href="{{route('student.create')}}" role="button">Add New Student</a>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                          <div class="col-112">
                            <?php 
                              $i=1;
                            ?>  
                            <table id="example1" class="table table-bordered table-striped">
                              <thead>
                              <tr>
                                <th width="5%">Serial No.</th>
                                <th>Member ID</th>
                                <th>Student Name</th>
                                <th>Student ID</th>
                                <th>Class</th>
                                <th>Gender</th>
                                <th>image</th>
                                <th>Action</th>
                              </tr>
                              </thead>
                              @foreach($studentData as $model)
                              <tr>
                                <td>{{$i++}}</td>
                                <td>{{$model->member_id}}</td>
                                <td>{{$model->name}}</td>
                                <td>{{$model->student_id}}</td>
                                <td>{{$model->class}}</td>
                                <td>{{$model->gender}}</td>
                                <td><img src="/uploads/{{$model->image}}" width="100" class="img-thumbnail"></td>

                                <td>
                                <a  class="btn btn-primary" href="{{route('student.edit',$model->id)}}" role="button">Edit</a>
                                {{ Form::open(['route'=>['student.destroy',$model->id], 'method'=>'delete' ,'class'=>'form-horizontal','files'=> true,'style' => 'display:inline',]) }}
                                {{ Form::submit('Delete',['class'=>'btn btn-danger','onclick' => 'return confirm("Are You Sure Want To Delete ?")']) }}
                                {{ Form::close() }}
                                <!-- <form method="POST" action="{{ route('category.destroy', [ 'id'=> $model->id ]) }}">
                                  @csrf
                                  <input type="hidden" name="delete" value="DELETE">
                                  <button type="submit" class="btn btn-danger btn-icon">
                                    <i data-feather="delete"></i>
                                  </button>
                                </form> -->
                                </td>
                              </tr>
                              @endforeach()
                            </table>
                          </div>  
                        </div>
                        <!-- /.card-body -->
                    </div>

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
</div>


@endsection