routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//front end home route
Route::get('/', function () {
    return view('frontend.index');
});

Auth::routes();

//backend home route
Route::get('/dashboard', 'HomeController@index')->name('home');

//register Route
Route::get('/new-register', function () {
    return view('auth.register');
});

//user list route
Route::get('/user-list', 'HomeController@userList')->name('user-list');

//Category Setup
Route::resource('/category', 'Setup\CategoryController')->parameter('category','id');

//Writer Setup
Route::resource('/writer', 'Setup\WriterController')->parameter('writer','id');

//Book
Route::resource('/book', 'Book\BookController')->parameter('book','id');

//Student
Route::resource('/student', 'Student\StudentController')->parameter('student','id');

//Book Issue
Route::resource('/book-issue', 'BookIssue\BookIssueController')->parameter('book-issue','id');
Route::get('/book-issue/get-book/{id}', 'BookIssue\BookIssueController@getCategoryWiseBook');
Route::get('/book-issue/get-class-wise-student/{id}', 'BookIssue\BookIssueController@getClassWiseStudent');

//book issue due list 
Route::get('/due-book-issue-list', 'BookIssue\BookIssueController@dueBookIssuelist')->name('due-book-issue-list');

//activity list 
Route::get('/activity-list', 'BookIssue\BookIssueController@activityList')->name('activity-list');

//fine list 
Route::get('/fine-list', 'BookIssue\BookIssueController@fineList')->name('fine-list');

app/Models/BookIssue.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Setup\Category;
use App\Models\Setup\Writer;
use App\Models\Student;
use App\Models\Book;

class BookIssue extends Model
{
    protected $fillable=['student_id','category_id','book_id','from_date','to_date','class','image','fine','created_by','updated_by'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function writer()
    {
        return $this->belongsTo(Writer::class);
    }

    public function student()
    {
        return $this->belongsTo(Student::class);
    }

    public function book()
    {
        return $this->belongsTo(Book::class);
    }
}

app/Http/Controllers/BookIssue/BookIssueController.php
<?php

namespace App\Http\Controllers\BookIssue;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use App\Models\BookIssue;
use App\Models\Student;
use App\Models\Book;
use App\Models\Setup\Category;
use App\Models\Setup\Writer;
use Auth;
use Illuminate\Support\Facades\DB;

class BookIssueController extends Controller
{

    public function index()
    {
        $bookIssueData=BookIssue::all();
        return view('backend.BookIssue.index',compact("bookIssueData"));
    }

    public function create()
    {
        $student=Student::all();
        $category=Category::get()->all();
        $writer=Writer::get()->all();
        return view('backend.BookIssue.create',compact("category","writer","student"));
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required',
            'category_id'=>'required',
            'student_id'=>'required',
            'book_id'=>'required',
            'class'=>'required',
            'from_date'=>'required',
            'to_date'=>'required',
        ]);
        //dd($request);
        $book_issue=new BookIssue();
        $book_issue->student_id=$request->student_id;
        $book_issue->category_id=$request->category_id;
        $book_issue->book_id=$request->book_id;
        $book_issue->class=$request->class;
        $book_issue->from_date=date("Y-m-d",strtotime($request->from_date));
        $book_issue->to_date=date("Y-m-d",strtotime($request->to_date));
        $book_issue->created_by=Auth::id();
        $book_issue->status="Issued";


        //file Upload
        if ($request->hasFile('file')){
            $file=$request->file('file');
            $extension=$file->getClientOriginalExtension();
            $fileName = time().'.'. $extension;
            $file->move('uploads',$fileName);
            $book_issue->image=$fileName;

        }
        else
        {
            $book_issue->image='';
        }

        $book_issue->save();
        return redirect(route('book-issue.index'))->with('success','Book Issue Has been Created Successfully');
    }

    // public function show($id)
    // {
    //     $book=Book::findorFail($id);
    //     return view('backend.book.show',compact("book"));
    // }

    public function edit($id)
    {
        $bookIssueData=BookIssue::findorFail($id);
        $student=Student::all();
        $category=Category::get()->all();
        $writer=Writer::get()->all();

        return view('backend.BookIssue.edit',compact("category","writer","student","bookIssueData"));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name'=>'required',
            'category_id'=>'required',
            'student_id'=>'required',
            'book_id'=>'required',
            'class'=>'required',
            'from_date'=>'required',
            'to_date'=>'required',
        ]);
        //dd($request);
        $file_name=$request->hidden_file;

        if ($request->hasFile('file')){
            $file=$request->file('file');
            $extension=$file->getClientOriginalExtension();
            $fileName = time().'.'. $extension;
            $file->move('uploads',$fileName);
            $image=$fileName;

        }
        else
        {
            $image=$file_name;
        }

        $edited_data=array(
            'student_id'=>$request->student_id,
            'category_id'=>$request->category_id,
            'book_id'=>$request->book_id,
            'class'=>$request->class,
            'from_date'=>date("Y-m-d",strtotime($request->from_date)),
            'to_date'=>date("Y-m-d",strtotime($request->to_date)),
            'status'=>$request->status,
            'fine'=>$request->fine,
            'image'=>$image,
            'updated_by'=>Auth::id()

        );

        BookIssue::whereId($id)->update($edited_data);
        return redirect(route('book-issue.index'))->with('success','Book Issue Has been Updated Successfully');
    }

    public function destroy($id)
    {
        $bookData=Book::findorFail($id);
        $bookData->delete();
        return redirect()->route('book.index')->with('success','Book Issue Has been Deleted Successfully');

    }

    //categoryWiseBook
    public function getCategoryWiseBook()
    {
        $id = $_GET['myID'];
        $res = DB::table('categories as a')
        ->select('b.*')
        ->leftjoin('books as b','b.category_id','=','a.id')
        ->where('b.category_id', $id)
        ->get();

        return response()->json($res);

    }

    //classWiseStudent
    public function getClassWiseStudent()
    {
        $id = $_GET['classID'];
        $res = DB::table('students')
        ->select('*')
        ->where('class', $id)
        ->get();

        return response()->json($res);

    }

    public function dueBookIssuelist()
    {
        $data= DB::table('book_issues as a')
            ->select('a.*','b.name','b.student_id as std_id','c.name as book_name','d.name as category_name')
            ->leftjoin('students as b','a.student_id','=','b.id')
            ->leftjoin('books as c','a.book_id','=','c.id')
            ->leftjoin('categories as d','a.category_id','=','d.id')
            ->whereRaw("DATE(a.to_date) < CURDATE()")
            ->get();
        //dd($data);
        return view('backend.BookIssue.due-book-issue-list',compact("data"));
    }

    public function activityList()
    {
        $data= DB::table('book_issues as a')
            ->select('a.*','c.name as book_name','d.name as category_name')
            ->leftjoin('students as b','a.student_id','=','b.id')
            ->leftjoin('books as c','a.book_id','=','c.id')
            ->leftjoin('categories as d','a.category_id','=','d.id')
            ->where('b.member_id',Auth::user()->member_id)
            ->get();
        //dd($data);
        return view('backend.BookIssue.activity-list',compact("data"));
    }

    public function fineList()
    {
        $data= DB::table('book_issues as a')
            ->select('a.*','b.*','c.name as book_name','d.name as category_name')
            ->leftjoin('students as b','a.student_id','=','b.id')
            ->leftjoin('books as c','a.book_id','=','c.id')
            ->leftjoin('categories as d','a.category_id','=','d.id')
            ->whereNotNull('a.fine')
            ->get();
        //dd($data);
        return view('backend.fine.fine-list',compact("data"));
    }
}

resources/views/backend/BookIssue/activity-list.blade.php
@extends('backend.layout.master')

@section('title', 'Activity List')

@section('content')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 >Due Book Issue List</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body">
                          <div class="col-112">
                            <?php 
                              $i=1;
                            ?>  
                            <table id="example1" class="table table-bordered table-striped">
                              <thead>
                              <tr>
                                <th width="5%">Serial No.</th>
                                <th>Book Name</th>
                                <th>Category</th>
                                <th>Issue Date</th>
                                <th>Due Date</th>
                                <th>Status</th>
                              </tr>
                              </thead>
                              @foreach($data as $model)
                              <tr>
                                <td>{{$i++}}</td>
                                <td>{{$model->book_name}}</td>
                                <td>{{$model->category_name}}</td>
                                <td>{{$model->from_date}}</td>
                                <td>{{$model->to_date}}</td>
                                <td>{{$model->status}}</td>
                                </td>
                              </tr>
                              @endforeach()
                            </table>
                          </div>  
                        </div>
                        <!-- /.card-body -->
                    </div>

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
</div>


@endsection

resources/views/backend/BookIssue/create.blade.php
@extends('backend.layout.master')

@section('title', 'Create Book Issue')

@section('content')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h3> Add New Book Issue Data</h3>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <form class="form-horizontal" method="POST" action ="{{route('book-issue.store')}}" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <!-- class -->
                                <div class="form-group row">
                                    <label for="class" class="col-sm-2 col-form-label">Class<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                        <select name="class" id='class_id' class="form-control" required>
                                            <option value="" selected>-Select Class-</option>
                                            <option value="6">Six</option>
                                            <option value="7">Seven</option>
                                            <option value="8">Eight</option>
                                            <option value="9">Nine</option>
                                            <option value="10">Ten</option>
                                        </select>
                                    </div>
                                </div>
                                <!-- studentname -->
                                <div class="form-group row">
                                    <label for="name" class="col-sm-2 col-form-label">Student Name<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                    <select name="student_id"  class="form-control" id="student" disabled >
                                        <option>Student List</option>
                                    </select>
                                    </div>
                                </div>
                                <!-- category -->
                                <div class="form-group row">
                                    <label for="category" class="col-sm-2 col-form-label">Category Name<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                        <select name="category_id" class="form-control" id="category"  required>
                                            <option value="" selected>-Select Category-</option>
                                            @foreach($category as $model)
                                                <option value="{{$model->id}}">{{$model->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <!-- book -->
                                <div class="form-group row">
                                    <label for="writer" class="col-sm-2 col-form-label">Book List<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                    <select name="book_id"  class="form-control" id="book" disabled >
                                        <option>Book List</option>
                                    </select>
                                    </div>
                                </div>
                                <!-- from date -->
                                <div class="form-group row">
                                    <label for="writer" class="col-sm-2 col-form-label">From Date<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                    <input type="text" id="orangeDateOfBirthForm" name="from_date" class="form-control validate" required>
                                    
                                    </div>
                                </div>
                                <!-- to date -->
                                <div class="form-group row">
                                    <label for="writer" class="col-sm-2 col-form-label">To Date<span style="color:red">*</span></label>
                                    <div class="col-sm-8">
                                    <input type="text" id="orangeDateOfBirth" name="to_date" class="form-control validate" required>
                                    
                                    </div>
                                </div>

                                <!-- Upload File -->
                                <div class="form-group row">
                                    <label for="file" class="col-sm-2 col-form-label">Image</label>
                                    <div class="col-sm-8">
                                    <input type="file" class="custom-file-upload" name="file">
                                    </div>
                                </div>

                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer float-right">
                                <input type="submit" class="btn btn-success ">
                                <a  class="btn btn-danger" href="{{route('book.create')}}" role="button">Reset</a>
                                <a  class="btn btn-primary" href="{{route('book.index')}}" role="button">Back</a>
                            </div>
                            <!-- /.card-footer -->
                        </form>
                        <!-- /.card-body -->
                    </div>

                </div>
            </div>
        </div>
            <!-- /.container-fluid -->
    </section>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
    // Get Book List 
     
      $(document).ready(function(){
        $('#category').change(function(){
           var category = $('#category').val();//alert(category);
           $('#book').html('');
            $.ajax({
              url:'get-book/{id}',
              type:'GET',
              data:{myID:category},
              dataType: "json",

              success:function(data)
              {
                //alert("category");
                $.each(data, function(key, book)
                 {     
                  // alert(city.city_name)
                  $('#book').prop('disabled', false).css('background','aliceblue').append('<option value="'+book.id+'">'+book.name+'</option>');
                });
              }
          });
        });

        $('#class_id').change(function(){
           var class_id = $('#class_id').val();//alert(class_id);
           $('#student').html('');
            $.ajax({
              url:'get-class-wise-student/{id}',
              type:'GET',
              data:{classID:class_id},
              dataType: "json",

              success:function(data)
              {
                //alert("category");
                $.each(data, function(key, student)
                 {     
                  // alert(city.city_name)
                  $('#student').prop('disabled', false).css('background','aliceblue').append('<option value="'+student.id+'">'+student.name+'('+student.student_id+')'+'</option>');
                });
              }
          });
        });
      });

      // Data Picker Initialization

     
      // Get Student
     
</script>
<script>
        $(document).ready(function(){
            // alert ('Cliecked');
            var from_date=$('input[name="from_date"]'); //our date input has the name "date"
            var to_date=$('input[name="to_date"]');
            var container=$('.bootstrap-iso form').length>0 ? $('.bootstrap-iso form').parent() : "body";
            var options={
                format: 'dd/mm/yyyy',
                container: container,
                changeYear: true,
                changeMonth: true,
                todayHighlight: true,
                autoclose: true,
                yearRange: "1930:2100"
            };
            from_date.datepicker(options);
            to_date.datepicker(options);
        });

</script>
@endsection

resources/views/backend/BookIssue/due-book-issue-list.blade.php
@extends('backend.layout.master')

@section('title', 'Due Book Issue List')

@section('content')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 >Due Book Issue List</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <!-- /.card-header -->
                        <div class="card-body">
                          <div class="col-112">
                            <?php 
                              $i=1;
                            ?>  
                            <table id="example1" class="table table-bordered table-striped">
                              <thead>
                              <tr>
                                <th width="5%">Serial No.</th>
                                <th>Student Name</th>
                                <th>Student ID</th>
                                <th>Class</th>
                                <th>Book Name</th>
                                <th>Category</th>
                                <th>Issue Date</th>
                                <th>Due Date</th>
                              </tr>
                              </thead>
                              @foreach($data as $model)
                              <tr>
                                <td>{{$i++}}</td>
                                <td>{{$model->name}}</td>
                                <td>{{$model->std_id}}</td>
                                <td>{{$model->class}}</td>
                                <td>{{$model->book_name}}</td>
                                <td>{{$model->category_name}}</td>
                                <td>{{$model->from_date}}</td>
                                <td>{{$model->to_date}}</td>

                                <!-- <form method="POST" action="{{ route('category.destroy', [ 'id'=> $model->id ]) }}">
                                  @csrf
                                  <input type="hidden" name="delete" value="DELETE">
                                  <button type="submit" class="btn btn-danger btn-icon">
                                    <i data-feather="delete"></i>
                                  </button>
                                </form> -->
                                </td>
                              </tr>
                              @endforeach()
                            </table>
                          </div>  
                        </div>
                        <!-- /.card-body -->
                    </div>

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
</div>


@endsection

resources/views/backend/BookIssue/index.blade.php
@extends('backend.layout.master')

@section('title', 'Book Issue List')

@section('content')

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Book Issue List</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header" style="text-align:right;">
                            <a  class="btn btn-primary" href="{{route('book-issue.create')}}" role="button">Add New Book Issue</a>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                          <div class="col-112">
                            <?php 
                              $i=1;
                            ?>  
                            <table id="example1" class="table table-bordered table-striped">
                              <thead>
                              <tr>
                                <th width="5%">Serial No.</th>
                                <th>Student Name</th>
                                <th>Student ID</th>
                                <th>Class</th>
                                <th>Book Name</th>
                                <th>Category</th>
                                <th>Issue Date</th>
                                <th>Due Date</th>
                                <th>Status</th>                                
                                <th>File</th>
                                <th>Action</th>
                              </tr>
                              </thead>
                              @foreach($bookIssueData as $model)
                              <tr>
                                <td>{{$i++}}</td>
                                <td>{{$model->student->name}}</td>
                                <td>{{$model->student->student_id}}</td>
                                <td>{{$model->class}}</td>
                                <td>{{$model->book->name}}</td>
                                <td>{{$model->category->name}}</td>
                                <td>{{$model->from_date}}</td>
                                <td>{{$model->to_date}}</td>
                                <td>{{$model->status}}</td>
                                <td><img src="/uploads/{{$model->image}}" width="100" download></td>
                                <td><a  class="btn btn-primary" href="{{route('book-issue.edit',$model->id)}}" role="button">Edit</a></td>

                                <!-- <form method="POST" action="{{ route('category.destroy', [ 'id'=> $model->id ]) }}">
                                  @csrf
                                  <input type="hidden" name="delete" value="DELETE">
                                  <button type="submit" class="btn btn-danger btn-icon">
                                    <i data-feather="delete"></i>
                                  </button>
                                </form> -->
                                </td>
                              </tr>
                              @endforeach()
                            </table>
                          </div>  
                        </div>
                        <!-- /.card-body -->
                    </div>

                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
</div>


@endsection