routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//front end home route
Route::get('/', function () {
    return view('frontend.index');
});

Auth::routes();

//backend home route
Route::get('/dashboard', 'HomeController@index')->name('home');

//register Route
Route::get('/new-register', function () {
    return view('auth.register');
});

//user list route
Route::get('/user-list', 'HomeController@userList')->name('user-list');

//Category Setup
Route::resource('/category', 'Setup\CategoryController')->parameter('category','id');

//Writer Setup
Route::resource('/writer', 'Setup\WriterController')->parameter('writer','id');

//Book
Route::resource('/book', 'Book\BookController')->parameter('book','id');

//Student
Route::resource('/student', 'Student\StudentController')->parameter('student','id');

//Book Issue
Route::resource('/book-issue', 'BookIssue\BookIssueController')->parameter('book-issue','id');
Route::get('/book-issue/get-book/{id}', 'BookIssue\BookIssueController@getCategoryWiseBook');
Route::get('/book-issue/get-class-wise-student/{id}', 'BookIssue\BookIssueController@getClassWiseStudent');

//book issue due list 
Route::get('/due-book-issue-list', 'BookIssue\BookIssueController@dueBookIssuelist')->name('due-book-issue-list');

//activity list 
Route::get('/activity-list', 'BookIssue\BookIssueController@activityList')->name('activity-list');

//fine list 
Route::get('/fine-list', 'BookIssue\BookIssueController@fineList')->name('fine-list');

resources/views/backend/layout/footer.blade.php
<!-- /.content-wrapper -->
<footer class="main-footer">
    <strong>Copyright &copy; 2021 <a href="http://adminlte.io">Sarwar Tushar</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.0.5
    </div>
  </footer>

resources/views/backend/layout/header.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>BookWorm | @yield('title')</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    
    
<!-- //date picker er jonno -->

<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>

<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<!-- // END date picker er jonno   -->
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('backend/plugins/fontawesome-free/css/all.min.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="{{asset('backend/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{asset('backend/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{{asset('backend/plugins/jqvmap/jqvmap.min.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('backend/dist/css/adminlte.min.css')}}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{asset('backend/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{asset('backend/plugins/daterangepicker/daterangepicker.css')}}">
    <!-- summernote -->
    <link rel="stylesheet" href="{{asset('backend/plugins/summernote/summernote-bs4.css')}}">
    <!-- Select2 -->
  <link rel="stylesheet" href="{{asset('../../backend/plugins/select2/css/select2.min.css')}}">
  <link rel="stylesheet" href="{{asset('../../backend/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
    
    
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- DataTables -->
  <link rel="stylesheet" href="{{asset('../../backend/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
  <link rel="stylesheet" href="{{asset('../../backend/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
</head>

resources/views/backend/layout/master.blade.php
@include('backend.layout.header')

<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

@include('backend.layout.navbar')

@include('backend.layout.sidebar')

@include('layouts.messages')

@yield('content')


  @include('backend.layout.footer')

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- ./wrapper -->
    </div>
    <!-- jQuery -->
    <script src="{{asset('backend/plugins/jquery/jquery.min.js')}}"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-- Bootstrap 4 -->
    <script src="{{asset('backend/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <!-- bs-custom-file-input -->
    <script src="{{asset('backend/plugins/bs-custom-file-input/bs-custom-file-input.min.js')}}"></script>
    <!-- DataTables -->
    <script src="{{asset('../../backend/plugins/datatables/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('../../backend/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{asset('../../backend/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('../../backend/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
    <!-- AdminLTE App -->
    <script src="{{asset('backend/dist/js/adminlte.min.js')}}"></script>
    <!-- Select2 -->
    <script src="{{asset('../../backend/plugins/select2/js/select2.full.min.js')}}"></script>
    <!-- date-range-picker -->
    <script src="{{asset('../../backend/plugins/daterangepicker/daterangepicker.js')}}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{{asset('backend/dist/js/demo.js')}}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            bsCustomFileInput.init();
        });
    </script>
    <script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });

  });

  //Date range picker

</script>

</body>
</html>

resources/views/backend/layout/navbar.blade.php
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{{url('/')}}" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      
      <!-- Notifications Dropdown Menu -->
      @guest
        <li class="nav-item">
            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
        </li>
        @if (Route::has('register'))
            <li class="nav-item">
                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
            </li>
        @endif
        @else
        <li class="nav-item dropdown">
            <a id="navbarDropdown" class="nav-link dropdown-toggle" style="background:orange;color:black" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                {{ Auth::user()->name }}
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="color:black">
                <a class="dropdown-item"  href="{{ route('logout') }}" 
                    onclick="event.preventDefault();
                                  document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                    @csrf
                </form>
                @if(Auth::user()->status=='1')
                <li>|</li>
                <li class="nav-item" style="background:orange">
                <a class="nav-link" href="{{ url('new-register') }}"style="color:black">{{ __('Register User') }}</a>
                </li>
                @endif
            </div>
        </li>
    @endguest

    </ul>
    
  </nav>
  <!-- /.navbar -->

resources/views/backend/layout/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="{{route('home')}}" class="brand-link">
  <img src="http://library.lo/bookworm.png"
          alt="AdminLTE Logo"
          class="brand-image img-circle elevation-3"
          style="opacity: .8">
    <span class="brand-text font-weight-light">BookWorm</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        @if(Auth::user()->image)
        <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        @endif
      </div>
      <div class="info">
        <a href="#" class="d-block">{{Auth::user()->name}}</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
              with font-awesome or any other icon font library -->

          <li class="nav-item">
              <a href="/dashboard" class="nav-link {{Request::is('dashboard') ? 'active' : ''}}">
              <i class="fas fa-columns"></i>
              <p>
                  DashBoard
              </p>
              </a>
          </li>
        @if(Auth::User()->status==1)
        <li class="nav-item has-treeview {{Request::is('category') || Request::is('writer') ? 'menu-open' : ''}}">
          <a href="#" class="nav-link {{Request::is('category') || Request::is('writer') ? 'active' : ''}}">
            <i class="nav-icon fas fa-edit"></i>
            <p>
              Setup
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{{url('category')}}" class="nav-link {{Request::is('category') ? 'active' : ''}}">
                <i class="fas fa-list-ol"></i>
                <p>Category</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{route('writer.index')}}" class="nav-link {{Request::is('writer') ? 'active' : ''}}">
                <i class="fas fa-user-edit"></i>
                <p>Writer</p>
              </a>
            </li>

          </ul>
        </li>
        @endif

        @if(Auth::User()->status==1)
        <li class="nav-item ">
          <a href="{{route('user-list')}}" class="nav-link {{Request::is('user-list') ? 'active' : ''}}">
            <i class="fas fa-users"></i>
            <p>
              User List
            </p>
          </a>
        </li>
        @endif

        <li class="nav-item ">
          <a href="{{route('book.index')}}" class="nav-link {{Request::is('book') ? 'active' : ''}}">
            <i class="fas fa-book-open"></i>
            <p>
              Book Info
            </p>
          </a>
        </li>

        @if(Auth::User()->status==1)
        <li class="nav-item ">
          <a href="{{route('student.index')}}" class="nav-link {{Request::is('student') ? 'active' : ''}}">
            <i class="fas fa-user-graduate"></i>
            <p>
              Student Info
            </p>
          </a>
        </li>
        @endif

        @if(Auth::User()->status==1)
        <li class="nav-item ">
          <a href="{{route('book-issue.index')}}" class="nav-link {{Request::is('book-issue') ? 'active' : ''}}">
            <i class="fas fa-book-medical"></i>
            <p>
              Issue Book
            </p>
          </a>
        </li>
        @endif

        @if(Auth::User()->status==1)
        <li class="nav-item ">
          <a href="{{route('due-book-issue-list')}}" class="nav-link {{Request::is('due-book-issue-list') ? 'active' : ''}}">
            <i class="fas fa-book"></i>
            <p>
              Due Book Issue List
            </p>
          </a>
        </li>
        @endif

        <li class="nav-item ">
          <a href="{{route('activity-list')}}" class="nav-link {{Request::is('activity-list') ? 'active' : ''}}">
            <i class="fas fa-chart-line"></i>
            <p>
              Activity List
            </p>
          </a>
        </li>

        @if(Auth::User()->status==1)
        <li class="nav-item ">
          <a href="{{route('fine-list')}}" class="nav-link {{Request::is('fine-list') ? 'active' : ''}}">
            <i class="fas fa-dollar-sign"></i>
            <p>
              Fine List
            </p>
          </a>
        </li>
        @endif
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>